# Generated by Django 4.2.7 on 2023-11-09 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='auth_type',
        ),
    ]
