# Generated by Django 4.2.7 on 2023-11-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='auth_type',
            field=models.CharField(choices=[('PhoneNumber', 'Phone Number'), ('Email', 'Email')], default='', max_length=100),
            preserve_default=False,
        ),
    ]
